// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.ufpb.ccae.dcx.lcc.tcc.model;

import br.ufpb.ccae.dcx.lcc.tcc.model.Challenge;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Challenge_Roo_Configurable {
    
    declare @type: Challenge: @Configurable;
    
}
